# Generated by Django 6.0.3 on 2026-03-29 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_update_application_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='postulaciones',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=255)),
                ('edad', models.IntegerField()),
                ('experiencia_ventas', models.CharField(max_length=100)),
                ('disponibilidad', models.TextField()),
                ('comentarios', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'postulaciones',
                'managed': False,
            },
        ),
    ]
