# Generated by Django 6.0.3 on 2026-03-30 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_update_application_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='postulaciones',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=255)),
                ('edad', models.IntegerField()),
                ('experiencia_ventas', models.CharField(max_length=100)),
                ('disponibilidad', models.TextField()),
                ('comentarios', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'postulaciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StitchApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=160, verbose_name='Nombre completo')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('phone', models.CharField(max_length=30, verbose_name='Teléfono')),
                ('experience', models.CharField(choices=[('sin_experiencia', 'Sin experiencia'), ('1_2', '1-2 años'), ('mas_3', '3+ años')], max_length=20, verbose_name='Experiencia (Años)')),
                ('cv', models.FileField(upload_to='cvs/', verbose_name='Adjuntar CV (PDF)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de postulación')),
            ],
            options={
                'verbose_name': 'Postulación (Stitch)',
                'verbose_name_plural': 'Postulaciones (Stitch)',
                'ordering': ['-created_at'],
            },
        ),
    ]
