# Generated by Django 6.0.3 on 2026-03-31 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_postulaciones'),
        ('jobs', '0003_postulaciones_stitchapplication'),
    ]

    operations = [
    ]
